apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test-pod
  namespace: edu-goofy-allen
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: postgres-cert-volume
      mountPath: /root/.postgresql
  volumes:
  - name: postgres-cert-volume
    secret:
      secretName: postgres-cert
      defaultMode: 384