apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 360
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py",  "migrate", "--no-input"]
        envFrom:
          - configMapRef:
              name: configmap
          - secretRef:
              name: django-secrets
      restartPolicy: Never