apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: <base64_encoded_secret_key>
  DATABASE_URL: <base64_encoded_database_url>
  postgresPassword: <base64_encoded_postgresPassword>
  username: <base64_encoded_username>
  database: <base64_encoded_database>

