apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1,15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-secrets
                    key: SECRET_KEY
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-secrets
                    key: DATABASE_URL
              - name: DEBUG
                value: "True"
              - name: ALLOWED_HOSTS
                value: "127.0.0.1,localhost,192.168.59.101"
          restartPolicy: OnFailure